openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
tags:
- name: Report
  description: 기업 및 산업 분석 관리 API
paths:
  /reports:
    get:
      tags:
      - Report
      summary: 보고서 조회
      description: 특정 보고서를 조회합니다.
      operationId: getReport
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      - name: category
        in: query
        required: true
        schema:
          type: string
      - name: createdAt
        in: query
        required: true
        schema:
          type: string
          format: date-time
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CompanyIndustryReportResponseDTO"
    put:
      tags:
      - Report
      summary: 보고서 업데이트
      description: 보고서를 업데이트합니다.
      operationId: updateReport
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      - name: category
        in: query
        required: true
        schema:
          type: string
      - name: createdAt
        in: query
        required: true
        schema:
          type: string
          format: date-time
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompanyIndustryReportCreateDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CompanyIndustryReportResponseDTO"
    post:
      tags:
      - Report
      summary: 보고서 생성
      description: 새로운 기업/산업 보고서를 생성합니다.
      operationId: createReport
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompanyIndustryReportCreateDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CompanyIndustryReportResponseDTO"
    delete:
      tags:
      - Report
      summary: 보고서 삭제
      description: 보고서를 삭제합니다.
      operationId: deleteReport
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      - name: category
        in: query
        required: true
        schema:
          type: string
      - name: createdAt
        in: query
        required: true
        schema:
          type: string
          format: date-time
      responses:
        "200":
          description: OK
  /reports/list:
    get:
      tags:
      - Report
      summary: 보고서 리스트 조회
      description: 보고서 리스트를 조회합니다.
      operationId: getReportList
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      - name: category
        in: query
        required: true
        schema:
          type: string
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 0
      - name: size
        in: query
        required: false
        schema:
          type: integer
          format: int32
          default: 10
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CompanyIndustryReportResponseDTO"
components:
  schemas:
    CompanyDetailDTO:
      required:
      - companyName
      type: object
      properties:
        companyName:
          type: string
          description: Company Name
          example: Day Company
        companyFeatures:
          type: string
          description: Company Features
          example: 수평적 구조
        companyIdealTalent:
          type: string
          description: Ideal Talent
          example: 도전을 즐기는 인재
        companyNews:
          type: string
          description: Company News
          example: 100억 투자 유치 성공
      description: DTO for CompanyDetail
    CompanyIndustryReportCreateDTO:
      required:
      - category
      type: object
      properties:
        category:
          type: string
          description: Category
          example: All
        companyDetails:
          type: array
          description: 회사 상세 정보 리스트
          items:
            $ref: "#/components/schemas/CompanyDetailDTO"
        industryDetails:
          type: array
          description: 산업 상세 정보 리스트
          items:
            $ref: "#/components/schemas/IndustryDetailDTO"
      description: DTO for creating a new CompanyIndustryReport
    IndustryDetailDTO:
      required:
      - industryType
      type: object
      properties:
        industryType:
          type: string
          description: Industry Type
          example: E-commerce
        industryFeatures:
          type: string
          description: Industry Features
        industryNews:
          type: string
          description: Industry News
      description: DTO for IndustryDetail
    CompanyIndustryReportResponseDTO:
      type: object
      properties:
        category:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        companyDetails:
          type: array
          items:
            $ref: "#/components/schemas/CompanyDetailDTO"
        industryDetails:
          type: array
          items:
            $ref: "#/components/schemas/IndustryDetailDTO"
      description: DTO for CompanyIndustryReport responses
