openapi: 3.0.1
info:
  title: PickMe-Records
  version: 2.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
security:
- BearerAuth: []
tags:
- name: Report
  description: 기업 및 산업 분석 관리 API
paths:
  /report:
    get:
      tags:
      - Report
      summary: 보고서 조회
      description: 특정 기업/산업 분석 보고서를 조회합니다.
      operationId: getReport
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      - name: reportId
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CompanyIndustryReportResponseDTO"
    put:
      tags:
      - Report
      summary: 보고서 업데이트
      description: 기업/산업 분석 보고서를 업데이트합니다.
      operationId: updateReport
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      - name: reportId
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompanyIndustryReportCreateDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CompanyIndustryReportResponseDTO"
    post:
      tags:
      - Report
      summary: 보고서 생성
      description: 새로운 기업/산업 분석 보고서를 생성합니다.
      operationId: createReport
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CompanyIndustryReportCreateDTO"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ReportIdResponseDTO"
    delete:
      tags:
      - Report
      summary: 보고서 삭제
      description: 기업/산업 분석 보고서를 삭제합니다.
      operationId: deleteReport
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      - name: reportId
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
  /report/sidebar:
    get:
      tags:
      - Report
      summary: 사이드바 데이터 조회
      description: 사이드바에 필요한 기업/산업 분석 보고서를 조회합니다.
      operationId: getSidebarData
      parameters:
      - name: Authorization
        in: header
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CompanyIndustryReportSidebarDTO"
components:
  schemas:
    CompanyDetailDTO:
      required:
      - companyName
      type: object
      properties:
        companyName:
          type: string
          description: Company Name
          example: Day Company
        companyFeatures:
          type: string
          description: Company Features
          example: 수평적 구조
        companyIdealTalent:
          type: string
          description: Ideal Talent
          example: 도전을 즐기는 인재
        companyNews:
          type: string
          description: Company News
          example: 100억 투자 유치 성공
      description: DTO for CompanyDetail
    CompanyIndustryReportCreateDTO:
      required:
      - category
      type: object
      properties:
        category:
          type: string
          description: Category
          example: All
        companyDetail:
          $ref: "#/components/schemas/CompanyDetailDTO"
        industryDetail:
          $ref: "#/components/schemas/IndustryDetailDTO"
      description: DTO for creating a new CompanyIndustryReport
    IndustryDetailDTO:
      required:
      - industryType
      type: object
      properties:
        industryType:
          type: string
          description: Industry Type
          example: E-commerce
        industryFeatures:
          type: string
          description: Industry Features
        industryNews:
          type: string
          description: Industry News
      description: DTO for IndustryDetail
    CompanyIndustryReportResponseDTO:
      type: object
      properties:
        category:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        companyDetail:
          $ref: "#/components/schemas/CompanyDetailDTO"
        industryDetail:
          $ref: "#/components/schemas/IndustryDetailDTO"
      description: DTO for CompanyIndustryReport responses
    ReportIdResponseDTO:
      type: object
      properties:
        reportId:
          type: string
      description: DTO for returning reportId
    CompanyIndustryReportSidebarDTO:
      type: object
      properties:
        reportId:
          type: string
          description: Report ID
        category:
          type: string
          description: Category
        createdAt:
          type: string
          description: Creation time
          format: date-time
        updatedAt:
          type: string
          description: Last update time
          format: date-time
      description: DTO for CompanyIndustryReport sidebar data
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
